### PR TITLE
add limitResponseLength caveat

### PR DESCRIPTION
**Pull request by brad-decker**
Adds a limitResponse caveat that slices an array response to the specified length.

### CODE REVIEW

**Review by rekmarks — CHANGES_REQUESTED** [review]
Given linting shenanigans, we should probably merge #96 first.

The caveat looks good though!

**Review by rekmarks — CHANGES_REQUESTED** [review]
I want to suggest we make the name more specific by changing it to `limitResponseLength`, but then this is good to go!

**Comment by brad-decker** [comment]
@rekmarks - done

**Comment by brad-decker** [comment]
p.s Github might not be showing there's another commit, but there is. :eyes:

**Comment by brad-decker** [comment]
Fixed with a rebase, change is now *actually* there

**Review by rekmarks — APPROVED** [review]
LGTM!

I think we need to introduce more extensive caveat validation (ala `PropTypes`, because do we really want a `limitResponseLength` value of `0` or `-1`?), but that'll be its own PR.

**Pull request merged**
