### PR TITLE
feat: add filterResponse deep compare with fast-deep-equal

### PR DESCRIPTION
**Pull request by shanejonas**

### CODE REVIEW

**Comment by Gudahtt** [comment]
@shanejonas Could you explain what this change is, and why it's being made?

**Comment by shanejonas** [comment]
Sure, this change extends the current `filterResponse` to support not just shallow arrays of strings, but deep compare of objects as well.

**Comment by shanejonas** [comment]
@rekmarks any reason why this was closed? continuing to support shallow strings only for filters doesn't sound like a long term solution?

**Comment by rekmarks** [comment]
Shoot, I just renamed the default branch and deleted `master`, forgetting that doing so closes open PRs 🤦‍♂️. Can you please reopen the PR against `main`? Sorry!

**Pull request closed without merging**
